### ISSUE TITLE
当一个文件夹目录下文件超过100个时 path_to_id(create=True)时回进入死循环

### ISSUE THREAD

**Issue by wangjunkai2022** [Quan666/PikPakAPI#17]
<img width="1111" alt="截屏2023-09-13 下午7 21 23" src="https://github.com/Quan666/PikPakAPI/assets/115545671/67d45f2b-b74b-4913-a946-7a4cf7ca6325">
这里 获取的next_page_token 永远相同无法获取到下一个目录的值 会死循环

**Comment by Quan666** [comment]
有请求响应样例吗

**Comment by wangjunkai2022** [comment]
我找到问题所在了。用源代码改了
<img width="642" alt="截屏2023-09-14 上午11 29 39" src="https://github.com/Quan666/PikPakAPI/assets/115545671/f0ac5fda-29df-481f-a598-763373ec9bfc">
这里的next_page_token 在pikpak的api中可能更改了 因为next_page_token 没有读取到 所有一直获取时是默认的next_page_token 所以返回的值是一样的。。会永远进入死循环。

**Comment by wangjunkai2022** [comment]
这里我也增加了
<img width="1152" alt="截屏2023-09-14 上午11 33 42" src="https://github.com/Quan666/PikPakAPI/assets/115545671/18fc9a2d-dd84-4210-9468-74e2f1bc8eaf">
判断 防止返回相同值的时候会死循环

**Comment by wangjunkai2022** [comment]
> 有请求响应样例吗

可以试试在一个文件夹下创建尽量多的文件夹 然后在此文件夹下进行查找 和创建新文件夹 就会进入这里 复现出这样的问题

**Comment by Quan666** [comment]
你可以把你修改的代码创建PR提交上来

**Comment by wangjunkai2022** [comment]
抱歉 我没有在github上传修改过的内容到原来的仓库中 我刚试了尝试clone此项目并在本地建了一个分支 当我上传时提示没有权限。不知道是不是我的操作不正确

**Comment by Quan666** [comment]
你应该fork仓库，fork后把你修改的代码上传至你的仓库，然后在到这个仓库创建pull request

**Comment by wangjunkai2022** [comment]
我这边已经创建并修改
<img width="1703" alt="截屏2023-09-21 下午8 07 52" src="https://github.com/Quan666/PikPakAPI/assets/115545671/1cfe5ef2-31f7-4fad-8d5e-e5f54cbc34e5">
接下来我在此仓库中没有找到对应的我的fork的代码 接下来不知道怎么操作。
<img width="1781" alt="截屏2023-09-21 下午8 07 03" src="https://github.com/Quan666/PikPakAPI/assets/115545671/04840e4f-a900-4742-b9ae-b3b0109519c6">

**Comment by Quan666** [comment]
你可以搜索下GitHub怎么创建pull request

**Comment by Patrick-Ze** [comment]
感谢，我也遇到了这个问题，来看发现已经解决了。其他人如果有类似问题的话在新的pip包发布前可以先用
`python -m pip install git+https://github.com/Quan666/PikPakAPI.git`
进行安装
