### ISSUE TITLE
[接口请求] 从离线列表中恢复下载

### ISSUE THREAD

**Issue by Wsine** [Quan666/PikPakAPI#2]
你好，我看到接口列表中有添加离线下载的操作以及获取离线下载列表的操作。如果一次添加的离线下载请求超过每天的免费次数会失败，因为可否有接口能恢复离线下载列表中的失败操作？

谢谢

**Comment by Quan666** [comment]
网页端有恢复这个操作吗？

**Comment by Wsine** [comment]
有的，在传输列表中有记录（应该类似于获取离线下载列表），然后对应的待下载文件旁边有一个重试按钮，可以在第二天的免费次数中恢复下载。

**Comment by Quan666** [comment]
> 有的，在传输列表中有记录（应该类似于获取离线下载列表），然后对应的待下载文件旁边有一个重试按钮，可以在第二天的免费次数中恢复下载。

好，我晚点注册个新账号试一试

**Comment by Wsine** [comment]
感谢，这样就可以利用 pikpak 做一些自动化的任务了。

**Comment by Quan666** [comment]
> 感谢，这样就可以利用 pikpak 做一些自动化的任务了。

加上了，你可以测试一下，还加了其他的 api

**Comment by Wsine** [comment]
好的，谢谢
