### ISSUE TITLE
PikpakException: Please add captcha before you register

### ISSUE THREAD

**Issue by bharathganji** [Quan666/PikPakAPI#29]
![image](https://github.com/Quan666/PikPakAPI/assets/59326887/4b739d34-c3dc-42fc-8624-71e939bfd68f)

steps to reproduce:
1. enter username in test.py file
2. enter password in test.py file
3. comment out httpx_client_args
4. open terminal and run ` py .\test.py`

**Comment by playingapi** [comment]
https://github.com/alist-org/alist/pull/6497

**Comment by Quan666** [comment]
尝试修复了，你试试 https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e

**Comment by Quan666** [comment]
> [alist-org/alist#6497](https://github.com/alist-org/alist/pull/6497)

没太看明白他这是怎么搞的

**Comment by playingapi** [comment]
> 尝试修复了，你试试 [6ada88b](https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e) Try to fix it, try it

{'error': 'captcha_invalid', 'error_code': 4002, 'error_description':

**Comment by Quan666** [comment]
> > 尝试修复了，你试试 [6ada88b](https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e) Try to fix it, try it
> 
> {'error': 'captcha_invalid', 'error_code': 4002, 'error_description':

你账号登陆是有验证码吗？

**Comment by playingapi** [comment]
> > > 尝试修复了，你试试 [6ada88b](https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e) Try to fix it, try it
> > 
> > 
> > {'error': 'captcha_invalid', 'error_code': 4002, 'error_description':
> 
> 你账号登陆是有验证码吗？

有

**Comment by playingapi** [comment]
> > > 尝试修复了，你试试 [6ada88b](https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e) Try to fix it, try it
> > 
> > 
> > {'error': 'captcha_invalid', 'error_code': 4002, 'error_description':
> 
> 你账号登陆是有验证码吗？

token无效

**Comment by Quan666** [comment]
再试试最新的代码
