### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by wangjunkai2022** [Quan666/PikPakAPI#30]
{'error': 'captcha_invalid', 'error_code': 4002, 'error_description': 'client_id:"YNxT9w7GMdWvEOKa"  meta:{key:"email"  value:"*************"}  meta:{key:"result"  value:"review"}  result:review', 'details': [{...}, {...}]}
<img width="464" alt="截屏2024-05-22 下午8 43 09" src="https://github.com/Quan666/PikPakAPI/assets/115545671/60a07e33-7cfb-458c-8f2f-771644e961cb">

**Comment by wangjunkai2022** [comment]
最新版 请求 'https://user.mypikpak.com/v1/auth/signin' 获取captcha_token报错。 我在网页登陆时加了一层滑动的人机验证。。。

**Comment by Quan666** [comment]
https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e
是试的这个吗

**Comment by Quan666** [comment]
我的账号登录没出现滑动验证码
你可以尝试更换IP看是否还是出现
