### ISSUE TITLE
近两个版本的pypi包发布失败

### ISSUE THREAD

**Issue by insomniacdoll** [Quan666/PikPakAPI#35]
如题，看日志应该是pypi那边的email配置问题，导致Actions执行失败，近两个版本的包没有发布到pypi。
![image](https://github.com/Quan666/PikPakAPI/assets/1646646/51da34e6-88d1-450d-82b8-744aa433e7b9)
![image](https://github.com/Quan666/PikPakAPI/assets/1646646/0ad15eff-631c-4d00-bd91-3ea000afbf2c)

**Comment by Quan666** [comment]
我邮箱问题，已经向pypi申诉了，但还没人处理

**Comment by Quan666** [comment]
`pip3 install git+https://github.com/Quan666/PikPakAPI.git`
可以先这样安装最新版本

**Comment by insomniacdoll** [comment]
> `pip3 install git+https://github.com/Quan666/PikPakAPI.git` 可以先这样安装最新版本

嗯，我目前就是这么安装的，只是仓库中没有正式版本号有点难受（
