### ISSUE TITLE
[Enhacement]接口请求

### ISSUE THREAD

**Issue by UltraSoundX** [Quan666/PikPakAPI#4]
您好，感谢您在此项目上付出的努力！
由于离线缓存下载时文件夹内有太多垃圾文件，我想将最大的文件（影视作品）移动到某个指定目录，特请求增加文件移动接口！再次对您的努力表示感谢！
附 接口信息
URI: https://api-drive.mypikpak.com/drive/v1/files:batchMove
Type:Post
Data:
{ids: ["VNFsQFbmBODmhBSfL2xlIVD0o1"], to: {}}

**Comment by Quan666** [comment]
可，这两天加上
