### ISSUE TITLE
web_content_link - 404 issue - download not working

### ISSUE THREAD

**Issue by bharathganji** [Quan666/PikPakAPI#40]
steps to reproduce:
1. fill username && password
2. add this line to test.py  -   print(json.dumps(await client.get_download_url("your_file_id")))
3. open link web_content_link - we can observe 404.

![image](https://github.com/user-attachments/assets/fb87d137-c1b3-4f2a-a79c-b2ac312850cf)

**Comment by Quan666** [comment]
This is an unknown restriction imposed by Pikpak. There is no particularly good solution at present.

**Comment by bharathganji** [comment]
> This is an unknown restriction imposed by Pikpak. There is no particularly good solution at present.

I can understand, so, currently we can't use download functionality right via api?

**Comment by Quan666** [comment]
> > This is an unknown restriction imposed by Pikpak. There is no particularly good solution at present.
> 
> I can understand, so, currently we can't use download functionality right via api?

yes

**Comment by pxia** [comment]
Seems like they changed the api for single file download, and it now requires captcha.

![Screenshot 2024-07-13 at 6 11 52 PM](https://github.com/user-attachments/assets/83093565-6acc-4430-a4cd-dc4e853cac71)

**Comment by Quan666** [comment]
> Seems like they changed the api for single file download, and it now requires captcha.
> 
> ![Screenshot 2024-07-13 at 6 11 52 PM](https://github.com/user-attachments/assets/83093565-6acc-4430-a4cd-dc4e853cac71)
> 

yes，and you also need to log in through the web api

**Comment by pxia** [comment]
> yes，and you also need to log in through the web api

What do you mean? We can still mimic it in python, right?

**Comment by Quan666** [comment]
> > yes，and you also need to log in through the web api
> 
> What do you mean? We can still mimic it in python, right?
> 

yes

**Comment by Quan666** [comment]
> > > > yes，and you also need to log in through the web api
> > > 
> > > 
> > > What do you mean? We can still mimic it in python, right?
> > 
> > 
> > yes
> 
> alist已经有人提交PR了，可以参考下？ [alist-org/alist#6775](https://github.com/alist-org/alist/pull/6775)

参考着修复了
