### ISSUE TITLE
pikpak 视频分级限流。

### ISSUE THREAD

**Issue by ericvlog** [Quan666/PikPakAPI#46]
我发现了一个问题，pikpak 官方播放器在播放一个视频时可以选择 4k, 1080p, 720p，480p 或自动画质的。

我在 stremio mediafusion 插件他是用你的 api 来实现的，但我在stremio播放视频时网路速度实时是 6MB/s， 同一个视频在 pikpak 官方播放是 10+MB/s, 很有可以 pikpakapi 已经自动用比较低的解析度来播放，而不是用原文件4k。

今天我用 alist 挂载的 pikpak 推送下载资源到 aria2， 明明同一个视频 80Gb 但推送到 aria2 只有大概 13Gb， 不知alist 是不是用你的api 来实现。

![image](https://github.com/user-attachments/assets/993c78cf-a540-45cc-836a-2831b3429681)
![image](https://github.com/user-attachments/assets/15c1bdd7-3b01-4955-b11b-69512cb4b275)

**Comment by Quan666** [comment]
alist都不是用Python写的，和我这关系不大，你可以自己抓包看看实际请求长什么样
