### ISSUE TITLE
pikpak api问题咨询

### ISSUE THREAD

**Issue by wangzhaoyang123** [Quan666/PikPakAPI#47]
您好，我一直在使用您的pikpak api项目，感觉对自己帮助很大，向和您有偿沟通一些东西，期待和您沟通

**Comment by Quan666** [comment]
不加微信，另外不建议在此留下微信号。
有什么问题可以直接问

**Comment by wangzhaoyang123** [comment]
今天下午的时候发现现在pikpak的api登录不上去了，想向您咨询一下如何解决这个问题，您这样如果查找到了解决方案可以告诉我一下吗?谢谢，真的很感谢您的项目

**Comment by Quan666** [comment]
是最新版本吗

**Comment by wangzhaoyang123** [comment]
对，我是使用的您的0.1.10分支，我看到您最新的版本是一个login分支，在这个分支里面是需要手动验证码的，有可以不使用手动验证的方案吗

**Comment by Quan666** [comment]
暂时没有，你账号是否频繁登录导致风控？
一般验证一次后很长一段时间都不需要再登陆

**Comment by wangzhaoyang123** [comment]
我准备是需要频繁切换账号登录的，您这边要是有好的解决方案可以在issue里面通知我一下吗？谢谢，非常感谢

**Comment by Quan666** [comment]
可以保存登录信息，来避免频繁登录

**Comment by hhsw2015** [comment]
能否实现登录的时候  自动过滑块验证  ？ 现在alist那边需要  refresh_token ,  这个登录了才有

**Comment by Quan666** [comment]
不想加入自动过滑块的，一旦后面pikpak验证码改动就得跟着改代码，太麻烦了

**Comment by fireinrain** [comment]
自动过滑块 必然导致大量人用程序过 会导致pikpak那边频繁修改  最后自动过失效 这样陷入了一个循环。。。

**Comment by hhsw2015** [comment]
> 不想加入自动过滑块的，一旦后面pikpak验证码改动就得跟着改代码，太麻烦了

可以加入一个开关  到时候变动的话就把这个开关关掉 不影响使用

能自动话还是好一点  手动操作太麻烦

**Comment by hhsw2015** [comment]
> 自动过滑块 必然导致大量人用程序过 会导致pikpak那边频繁修改 最后自动过失效 这样陷入了一个循环。。。

pikpak也无法判断你是不是程序自动过掉的

**Comment by Quan666** [comment]
成本太高了
