### ISSUE TITLE
好像又不行了

### ISSUE THREAD

**Issue by zhiyou007** [Quan666/PikPakAPI#48]
{"error":"captcha_invalid","error_code":4002,"error_description":"Aborted - Your operation is too frequent, please try again later","details":[{"@type":"type.googleapis.com\/google.rpc.ErrorInfo","reason":"Aborted - Your operation is too frequent, please try again later","domain":"","metadata":[]},{"@type":"type.googleapis.com\/google.rpc.LocalizedMessage","locale":"en","message":"The safety verification has failed. Please try again"}]}}

**Comment by Quan666** [comment]
用的login分支的代码吗

**Comment by bharathganji** [comment]
i was also observing same, i was using main branch code

**Comment by Quan666** [comment]
> i was also observing same, i was using main branch code

试试 [login](https://github.com/Quan666/PikPakAPI/tree/login)

**Comment by bharathganji** [comment]
> > i was also observing same, i was using main branch code
> 
> Try [to login](https://github.com/Quan666/PikPakAPI/tree/login)

with this code i am seeing, do we need to enter captcha manually or just an byass mechanism !!?

**Comment by Quan666** [comment]
> > > i was also observing same, i was using main branch code
> > 
> > 
> > Try [to login](https://github.com/Quan666/PikPakAPI/tree/login)
> 
> with this code i am seeing, do we need to enter captcha manually or just an byass mechanism !!? [65ff9f0](https://github.com/Quan666/PikPakAPI/commit/65ff9f0add922e86dd55ad098a86f1ff47115b85)

You need to manually pass the verification code and then get the result

**Comment by bharathganji** [comment]
nope , login branch code was not working

these looks like restrictions on accounts , mine was premium account.
![image](https://github.com/user-attachments/assets/5fb7df5c-b57e-4f04-b3bf-6bce0a081521)

**Comment by Three-taile-dragon** [comment]
> nope , login branch code was not working
> 
> these looks like restrictions on accounts , mine was premium account.
> 
> and even after solving captcha, still same error, so i think even we mimic same action in code , it might not work and also in code it not falling into captch imput block. ![image](https://private-user-images.githubusercontent.com/59326887/358892207-5fb7df5c-b57e-4f04-b3bf-6bce0a081521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5Njk3NzcsIm5iZiI6MTcyMzk2OTQ3NywicGF0aCI6Ii81OTMyNjg4Ny8zNTg4OTIyMDctNWZiN2RmNWMtYjU3ZS00ZjA0LWIzYmYtNmJjZTBhMDgxNTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA4MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjdlNDU5MmNiNmEwZjcxYTI0ZjIwYmJiYTM2YzEyNDg2NmU1NDYzMzQwZDkxNzczMDQzYjEwOTYxNTM2YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.88ydpPKlGmN556c0n2YbocEmPGLPfW5xQqJK8Cf4HRA)

The error pictured here is encountering an official PikPak restriction on the login interface, and you'll need to wait about 24 hours for it to be lifted. Note that multiple attempts will cause the IP to be winded as well. The solution now is to use a third-party authorized account, such as a Google account.
