### ISSUE TITLE
同步方法

### ISSUE THREAD

**Issue by UltraSoundX** [Quan666/PikPakAPI#5]
尊敬的作者您好，很感谢您能够新增相关接口，但出于调试需要，我注意到您移除了同步方法，我能否请求新增同步方法？

**Comment by Quan666** [comment]
> 尊敬的作者您好，很感谢您能够新增相关接口，但出于调试需要，我注意到您移除了同步方法，我能否请求新增同步方法？

同时维护两份代码比较麻烦。
异步也可以像同步一样使用的，你可以参考test.py
