### ISSUE TITLE
获得流媒体连接

### ISSUE THREAD

**Issue by vjrmwe** [Quan666/PikPakAPI#7]
请问一下，用get_download_url获得的下载链接，在浏览器中可以下载。但想要直接用potplayer打开会显示503错误。
对比了一下api获得的下载链接和在pikpak网页中请求的连接，有一些区别。

对比了二者的请求header，pikpak网页中多了x-captcha-token这一项，是因为pikpak最近增加了验证码吗？请问要如何获得这个x-captcha-token。谢谢！

**Comment by Quan666** [comment]
应该和 x-captcha-token 关系不大
我测试了能正常播放，你链接是不是过期了
